### PR TITLE
Megaparsec

### PR DESCRIPTION
**Pull request by PierreR**

### CODE REVIEW

**Comment by PierreR** [comment]
PS: we should probably use `parseErrorPretty'` to get prettier parsing error.

**Comment by PierreR** [comment]
The usage of the megaparsec lexer seems to speed the parsing. Tests are still green ... but it is still quite slower compared to master.

**Comment by ocharles** [comment]
Could you describe what this PR is for? I'm not quite following. Is it a development of my branch?

Also, did you mean to create a PR against my fork, or for the official `dhall-haskell` repository?

**Comment by PierreR** [comment]
I meant to create a PR against your fork to improve the current megaparsec PR (from the official `dhall-haskell`) and getting some approval from you about these changes.

I guess this is not the correct approach ?

Maybe I should wait for the PR to be in a better shape performance wise ? I thought I could try to improve the situation a bit but it is still twice slower. 

Anyhow, I will probably stop and wait for you to come up with something clever. The whole `Chunk` business should be removed I guess ?

Sorry if my attempt to help had the opposite effect ;-)

**Comment by ocharles** [comment]
Ok! 

> I meant to create a PR against your fork to improve the current megaparsec PR (from the official dhall-haskell) and getting some approval from you about these changes.

For that, you need to use `ollie/megaparsec` as the base. I've just changed it. This helps me see just the differences between my branch and yours.

> I guess this is not the correct approach ?

This approach is fine, you just need to write a description to help me know what I'm looking at :smile: 

There are some useful changes in this PR, so I'm going to hand pick them. The `sc` stuff is quite specific, so I think we need to be careful that is well motivated. For now, I'm going to leave that out - I think ultimately we will need to have a separate performance-only branch. The changes here to use `megaparsec` for all parts of `dhall` is very helpful though, thank you!

**Pull request closed without merging**
